# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc64e050e89bc8c6c2671103e800595bf3e47e8d679c75b98b762a73ac6d8a011813b3f29a0c7afd5ca3a331bb1ad21f04b051561dcb6e6bd33b4ca2322dd681

test:
  secret_key_base: 7a306835fd490c2a0aabd41a2a7d05e84f8771038ee30c1fea40857e20a18205e5004d79149c2db94af77269f8ed3487d1938c535c59604212755e8c8761fe2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
